# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ngduc/vercel-deploy-action@master
        id: vercel-deployment
        with:
          vercel-cli: now
          vercel-token: ${{ secrets.ZEIT_TOKEN }} # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} #Optional
          vercel-org-id: ${{ secrets.ZEIT_ORG_ID }} #Required
          vercel-project-id: ${{ secrets.ZEIT_PROJECT_ID }} #Required

      - name: Cleanup scheduling
        uses: ngduc/clean-up-action@master
        with:
          projectId: ngducParcelUI # set your unique projectId, example: myProjectId1
          expiryMins: 1440 # after X minutes, invoke the below URL endpoint.
          method: 'DELETE' # (required) one of these methods: GET, POST, PUT, PATCH, DELETE
          url: https://api.vercel.com/v11/now/deployments/remove?url=${{ steps.vercel-deployment.outputs.preview-url-host }} # (required) some URL endpoint to clean up resources.
          headers: '{ "Authorization": "Bearer ${{ secrets.VERCEL_TOKEN }}" }' # headers (JSON string).
          payload: '' # payload for url (JSON string).
