# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/now-deployment@v2
        with:
          zeit-token: ${{ secrets.ZEIT_TOKEN }} # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} #Optional
          now-org-id: ${{ secrets.ZEIT_ORG_ID }} #Required
          now-project-id: ${{ secrets.ZEIT_PROJECT_ID }} #Required

      - name: Clean up
        uses: ngduc/clean-up-action@master
        with:
          userId: ngducParcelUI # your unique userId
          expiryMins: 1 # after X minutes, invoke URL to clean up
          method: 'POST' # (required) one of these methods: GET, POST, PUT, PATCH, DELETE
          url: https://some.cleanup.api.endpoint # (required) some URL endpoint to clean up resources.
          payload: '{ "someResourceId": 1234 }' # payload for url (JSON string).
